import { Resend } from 'resend'
import { RESEND_API_KEY, NEXT_PUBLIC_APP_URL } from '@/lib/env'

const resend = new Resend(RESEND_API_KEY)

/**
 * HTML-escape a string to prevent XSS in email templates.
 * Escapes: & < > " '
 */
function escapeHtml(unsafe: string): string {
  return unsafe
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;')
}

/**
 * Sanitize a string for use in email subject line.
 * Removes newlines/carriage returns (prevent header injection) and truncates.
 */
function sanitizeSubject(text: string, maxLength: number = 50): string {
  return text
    .replace(/[\r\n]+/g, ' ')
    .trim()
    .slice(0, maxLength)
}

export async function sendMagicLink(email: string, magicLink: string) {
  // Magic link is generated by Supabase, but still escape for safety
  const safeLink = encodeURI(magicLink)

  const { data, error } = await resend.emails.send({
    from: 'Juno <noreply@yourdomain.com>', // Update with your domain
    to: email,
    subject: 'Sign in to Juno',
    html: `
      <h1>Welcome to Juno!</h1>
      <p>Click the link below to sign in:</p>
      <a href="${safeLink}" style="display: inline-block; background: #16a34a; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px;">
        Sign In
      </a>
      <p style="color: #666; margin-top: 24px;">
        This link expires in 1 hour.
      </p>
    `,
  })

  if (error) {
    console.error('Failed to send magic link:', error)
    throw error
  }

  return data
}

export async function sendPostingReminder(
  email: string,
  coachName: string,
  contentPreview: string,
  contentId: string,
  options: { hasWarning?: boolean; warningReasons?: string[] } = {}
) {
  const appUrl = NEXT_PUBLIC_APP_URL
  const { hasWarning = false, warningReasons = [] } = options

  // Escape user-supplied content to prevent XSS
  const safeCoachName = escapeHtml(coachName || 'there')
  const safeContentPreview = escapeHtml(contentPreview)
  // For email subject: sanitize but don't HTML-escape (subjects are plain text)
  const safeSubjectPreview = sanitizeSubject(contentPreview, 50)
  // contentId should be a UUID, but escape anyway
  const safeContentId = encodeURIComponent(contentId)

  // Build warning banner HTML if there are moderation concerns
  const warningBannerHtml = hasWarning
    ? `
      <div style="background: #fef3c7; border: 1px solid #f59e0b; padding: 12px 16px; border-radius: 8px; margin: 16px 0;">
        <p style="margin: 0 0 8px 0; font-weight: bold; color: #92400e;">Review Recommended</p>
        <p style="margin: 0; color: #92400e; font-size: 14px;">
          This content has moderation flags: ${escapeHtml(warningReasons.join(', '))}
        </p>
      </div>
    `
    : ''

  // Only show copy button for green content; yellow content needs review first
  const copyButtonHtml = hasWarning
    ? ''
    : `
        <a href="${appUrl}/content/${safeContentId}" style="display: inline-block; background: #16a34a; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; margin-right: 8px;">
          Copy to Clipboard
        </a>
      `

  const { data, error } = await resend.emails.send({
    from: 'Juno <noreply@yourdomain.com>', // Update with your domain
    to: email,
    subject: hasWarning
      ? `Review needed: ${safeSubjectPreview}...`
      : `Time to post: ${safeSubjectPreview}...`,
    html: `
      <p>Hey ${safeCoachName},</p>
      <p>${hasWarning ? 'Your scheduled post needs a quick review before posting.' : 'Your scheduled post is ready to go live!'}</p>

      ${warningBannerHtml}

      <div style="background: #f3f4f6; padding: 16px; border-radius: 8px; margin: 16px 0;">
        <p style="margin: 0; white-space: pre-wrap;">${safeContentPreview}</p>
      </div>

      <p>
        ${copyButtonHtml}
        <a href="${appUrl}/drafts" style="display: inline-block; background: ${hasWarning ? '#16a34a' : '#6b7280'}; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; margin-right: 8px;">
          ${hasWarning ? 'Edit in Juno' : 'View in Juno'}
        </a>
        <a href="https://instagram.com" target="_blank" style="display: inline-block; background: #e11d48; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px;">
          Open Instagram
        </a>
      </p>

      <hr style="margin: 24px 0; border: none; border-top: 1px solid #e5e7eb;" />

      <p style="color: #666; font-size: 14px;">
        Juno - AI Chief of Staff for Coaches
      </p>
    `,
  })

  if (error) {
    console.error('Failed to send posting reminder:', error)
    throw error
  }

  return data
}
